version: "3"
services:

  frontend:
    container_name: social-frontend
    image: prashrex/social-frontend
    restart: always
    build: 
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    
    networks:
      - node-webapp-network

  nodeapp:
    container_name: social-backend
    image: prashrex/social-backend
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - node-webapp-network
    environment:
      - MONGO_DB_HOST_NAME=mongodb://mongodb:27017/socialblend

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - node-webapp-network


networks:
  node-webapp-network:
    driver: bridge