version: "3"
services:
  nodeapp:
    container_name: social-backend
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - node-webapp-network
    
    links:
      - nodeapp
    depends_on:
      - nodeapp
      
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"

    networks:
      - node-webapp-network


networks:
  node-webapp-network:
    driver: bridge