# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - versys

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c1516232cb4e46acb765c0861a59d360 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_31718e67d38f49dbb02b7785b0e7a039 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c1516232cb4e46acb765c0861a59d360 }}/mongo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'versys'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_665b9ce6cb7b4851941cfa823e7a7749 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c1516232cb4e46acb765c0861a59d360 }}/mongo:${{ github.sha }}'